### ISSUE TITLE
Copyright holder and license

### ISSUE THREAD

**Issue by marcelometal** [tsuru/prometheus-as-a-service#1]
Hi,
Could you please add LICENSE file and put the copyright holder and license inside each file?

This way there is no chance of someone stumbling across a piece of code without being exposed to the license.

Thanks!

**Comment by renatosis** [comment]
Hi @marcelometal , I've added the license. Thank you!

**Comment by marcelometal** [comment]
Ref: d28a789209f51cc79375884bd442bd6e93876c7c
